### ISSUE TITLE
Edição Conteúdos Inglês

### ISSUE THREAD

**Issue by vascosilverio** [iptomar/Tech-Art-F#90]

**Comment by TiagoDCMorgado** [comment]
PR-> https://github.com/iptomar/Tech-Art-F/pull/119

Query de update para os textos em ingles

`UPDATE technart.areas_website
SET titulo='Missão e Objetivos', texto='<p>Test TECHN&amp;ART conducts research in the domains of Heritage Safeguarding and Valorization, both in experimental development and applied research.<br><br>This R&amp;D unit has the following mission:<br><br><strong>a) </strong>To contribute to the consolidation of IPT training programs within the listed scientific domains;<br><br><strong>b) </strong>To contribute to the solid training of students by strengthening collaboration between the scientific research work carried out by TECHN&amp;ART researchers;<br><br><strong>c) </strong>To disseminate scientific, technological, and artistic culture through the organization of conferences, colloquiums, seminars, exhibitions, and cultural sessions;<br><br><strong>d) </strong>To promote advanced training of human resources, fostering their constant scientific and cultural valorization;<br><br><strong>e) </strong>To establish interinstitutional cooperation with national and international entities;<br><br><strong>f) </strong>To effectively utilize the funding it receives and other available resources;<br><br><strong>g) </strong>To provide services to the community within the scope of its activities.</p>', fotografia='662164ddd1f63_images2.jpg', titulo_en='Mission and Objectives', texto_en='<p>Test TECHN&amp;ART conducts research in the domains of Heritage Safeguarding and Valorization, both in experimental development and applied research.<br><br>This R&amp;D unit has the following mission:<br><br><strong>a) </strong>To contribute to the consolidation of IPT training programs within the listed scientific domains;<br><br><strong>b) </strong>To contribute to the solid training of students by strengthening collaboration between the scientific research work carried out by TECHN&amp;ART researchers;<br><br><strong>c) </strong>To disseminate scientific, technological, and artistic culture through the organization of conferences, colloquiums, seminars, exhibitions, and cultural sessions;<br><br><strong>d) </strong>To promote advanced training of human resources, fostering their constant scientific and cultural valorization;<br><br><strong>e) </strong>To establish interinstitutional cooperation with national and international entities;<br><br><strong>f) </strong>To effectively utilize the funding it receives and other available resources;<br><br><strong>g) </strong>To provide services to the community within the scope of its activities.</p>'
WHERE id=1;
UPDATE technart.areas_website
SET titulo='Eixos de Investigação ', texto='

                        <p>O Centro de Tecnologia, Restauro e Valorização das Artes desenvolve estratégias e metodologias de investigação no âmbito de duas linhas temáticas:</p>

                        <p class="text-uppercase"><b>a) Salvaguarda</b></p>
                        <p class="text-uppercase"><b>b) Valorização do Património Artístico e Cultural</b></p>
                        <br><br>
                        <p>A linha temática da <b>Salvaguarda</b> é constituída por duas linhas de ação: <b>a1) Conservação e Restauro</b> e <b>a2) Caraterização e Contextualização do Património</b>:</p>


                        <p><b>a1) </b><b>Conservação e Restauro –</b> esta linha de investigação sustenta-se nos estudos de na intervenção de conservação e restauro no património artístico móvel e integrado, e onde as questões relacionadas com as metodologias, materiais, tecnologia e ética estão sistematicamente em discussão. Esta linha reúne conservadores restauradores e investigadores que direta ou indiretamente participam nos projetos de investigação, desenvolvimento e intervenção para a salvaguarda do património artístico e cultural;</p>
                        <p><b>a2) </b><b>Caraterização e Contextualização do Património –</b> esta linha de investigação sustenta-se nos estudos culturais, arqueológicos, históricos, artísticos, literários e também de caraterização física, química e biológica dos materiais e da respetiva alteração e alterabilidade da compatibilidade química e estrutural dos suportes a preservar e dos novos materiais a aplicar, considerando o meio de proveniência e também da sua preservação. Esta linha reúne investigadores de diferentes formações que estudam, contextualizam e caracterizam o património material, imaterial e natural.</p>
                        <br>
                        <p>A linha temática da <b>Valorização do Património Artístico e Cultural</b> reúne as linhas de ação:<b> b1) Didática, Tecnologia e Comunicação</b> e <b>b2) Design e Inovação:</b></p>
                        <p><b>b1) </b><b>Didática, Tecnologia e Comunicação</b> – esta linha de investigação sustenta-se nos estudos da educação, sensibilização e difusão do património cultural e artístico e respetiva preservação, a diferentes escalas. No quadro da didática, pretende-se uma simbiose entre o património, a interpretação patrimonial e o turismo numa lógica sustentável. Visa-se, assim, proporcionar aprendizagens ativas e integradas através da interpretação das manifestações do património cultural (material e imaterial), com elevado valor científico, didático, patrimonial e turístico. A gestão patrimonial na ótica da fruição proporcionará conhecimentos sobre as dinâmicas sociais e culturais da contemporaneidade. Assim, esta linha de investigação, pode ser integrada na interação entre contextos de promoção da aprendizagem através da exploração de conexões didáticas, tecnológicas e comunicacionais. Estas metodologias e estratégias <i>englobam e-learning, mobile-learning</i>, objetos de aprendizagem, bibliotecas e repositórios de conteúdos digitais e <i> gamification</i>. Incluem-se ainda os ambientes imersivos, realidade aumentada, realidade virtual, sistemas de informação, sistemas multimédia e hipermédia, apps. Esta linha de ação reúne investigadores no âmbito do turismo cultural, do cinema e vídeo documental, do design e da informática;</p>

                        <p><b>b2) </b><b>Design e Inovação</b> – respeita à componente criativa, responde às funções estéticas, práticas e simbólicas dos produtos ou projetos e tem compromisso com a sociedade e sua envolvente de forma sustentável, inclusiva e inovadora. Esta linha considera aspetos tecnológicos, sociais, económicos e culturais, e trabalha com a forma e a função, tanto na comunicação como no produto, agindo em consonância com as necessidades materiais e culturais da sociedade. Reporta também formas de expressão e manifestações artísticas e culturais, tangíveis e intangíveis; no sentido de perpetuar a memória, sintetizada nas diversas manifestações, bem como descodificar ou reinterpretar o património à luz dos entendimentos, conceitos e linguagens atuais.</p>

                        <p>Estas linhas de ação complementam-se e imbricam-se para que o todo que a missão do TECHN&amp;ART seja coerente e tire partido do visando a transferência de conhecimento, de competências e de experiências de todas/os as/os investigadoras/es e colaboradoras/es do nosso centro.</p>

                    ', fotografia='eixos.jpg', titulo_en='Research Axes', texto_en='<p>The Center for Technology, Restoration, and Valorization of the Arts develops research strategies and methodologies within two thematic lines:</p>

<p class="text-uppercase"><b>a) Safeguarding</b></p>
<p class="text-uppercase"><b>b) Valorization of Artistic and Cultural Heritage</b></p>
<br><br>
<p>The thematic line of <b>Safeguarding</b> consists of two lines of action: <b>a1) Conservation and Restoration</b> and <b>a2) Characterization and Contextualization of Heritage</b>:</p>

<p><b>a1) </b><b>Conservation and Restoration –</b> this research line is based on studies of conservation and restoration intervention in movable and integrated artistic heritage, where issues related to methodologies, materials, technology, and ethics are systematically discussed. This line brings together conservators-restorers and researchers who directly or indirectly participate in research, development, and intervention projects for the safeguarding of artistic and cultural heritage;</p>
<p><b>a2) </b><b>Characterization and Contextualization of Heritage –</b> this research line is based on cultural, archaeological, historical, artistic, literary studies, as well as physical, chemical, and biological characterization of materials and their alteration and alterability, considering the chemical and structural compatibility of the supports to be preserved and the new materials to be applied, considering the origin environment and their preservation. This line brings together researchers from different backgrounds who study, contextualize, and characterize material, immaterial, and natural heritage.</p>
<br>
<p>The thematic line of <b>Valorization of Artistic and Cultural Heritage</b> gathers the lines of action: <b>b1) Didactics, Technology, and Communication</b> and <b>b2) Design and Innovation:</b></p>

<p><b>b1) </b><b>Didactics, Technology, and Communication –</b> this research line is based on studies of education, awareness, and dissemination of cultural and artistic heritage and its preservation, at different scales. In the framework of didactics, a symbiosis between heritage, heritage interpretation, and tourism in a sustainable logic is intended. The aim is to provide active and integrated learning through the interpretation of cultural heritage manifestations (material and immaterial), with high scientific, didactic, heritage, and touristic value. Heritage management from the perspective of enjoyment will provide knowledge about the social and cultural dynamics of contemporaneity. Thus, this research line can be integrated into the interaction between learning promotion contexts through the exploration of didactic, technological, and communicational connections. These methodologies and strategies encompass e-learning, mobile-learning, learning objects, libraries and digital content repositories, and gamification. They also include immersive environments, augmented reality, virtual reality, information systems, multimedia, and hypermedia systems, apps. This line of action brings together researchers in the field of cultural tourism, documentary cinema and video, design, and computer science;</p>

<p><b>b2) </b><b>Design and Innovation –</b> respects the creative component, responds to the aesthetic, practical, and symbolic functions of products or projects, and is committed to society and its environment in a sustainable, inclusive, and innovative way. This line considers technological, social, economic, and cultural aspects, and works with form and function, both in communication and in the product, acting in line with the material and cultural needs of society. It also refers to forms of expression and artistic and cultural manifestations, tangible and intangible; in order to perpetuate memory, synthesized in various manifestations, as well as to decode or reinterpret heritage in light of current understandings, concepts, and languages.</p>

<p>These lines of action complement and interweave so that the whole of TECHN&amp;ART''s mission is coherent and takes advantage of knowledge transfer, skills, and experiences from all researchers and collaborators in our center.</p>
'
WHERE id=3;
UPDATE technart.areas_website
SET titulo='Estrutura Orgânica', texto='<p>A atividade do Techn&amp;Art é suportada pelos seguintes órgãos de direção, gestão e administração:<br><br><strong>Diretor</strong><br><a href="#">Célio Gonçalo Marques</a>, Tecnologias de Informação e Comunicação<br><br><strong>Diretora Adjunta</strong><br><a href="#">Hermínia Maria Pimenta Ferreira Sol</a>, Literatura<br><br><strong>Secretário Administrativo</strong><br>Hirondina Alves São Pedro<br><br><strong>Conselho Diretivo</strong><br>Composto pelo Diretor, pela Diretora Adjunta e por:<br><a href="#">Ricardo Pereira Triães</a>, Conservação e Restauro<br><a href="#">Eunice Ferreira Ramos Lopes</a>, Turismo<br><a href="#">Regina Aparecida Delfino</a>, Artes Gráficas<br><a href="#">Marta Margarida S. Dionísio</a>, Línguas<br><a href="#">Ana Cláudia Pires da Silva</a>, Gestão<br><br><strong>Conselho Científico</strong><br>Composto por todos os membros integrados.<br><br><strong>Conselho Consultivo</strong><br>Ana María Calvo Manuel, Faculdade de Belas Artes da Universidade Completense de Madrid, Espanha.<br>Chao Gejin, Instituto de Tradição Oral da Academia Chinesa de Ciências Sociais.<br>José Julio García Arranz, Universidade da Estremadura, Espanha.<br>Laurent Tissot, Universidade de Neuchântel, Suíça.<br>Maria Filomena Guerra, Universidade Panthéon Sorbonne, Nanterre, França.<br>Zoltán Somhegyi, Universidade Károli Gáspár, Budapeste, Hungria.<br><br>&nbsp;</p>, fotografia = ? ', fotografia='estrutura.jpg', titulo_en='Organic Structure', texto_en='<p>Techn&amp;Art''s activity is supported by the following organs of direction, management, and administration:<br><br><strong>Director</strong><br><a href="#">Célio Gonçalo Marques</a>, Information and Communication Technologies<br><br><strong>Deputy Director</strong><br><a href="#">Hermínia Maria Pimenta Ferreira Sol</a>, Literature<br><br><strong>Administrative Secretary</strong><br>Hirondina Alves São Pedro<br><br><strong>Board of Directors</strong><br>Composed of the Director, the Deputy Director, and:<br><a href="#">Ricardo Pereira Triães</a>, Conservation and Restoration<br><a href="#">Eunice Ferreira Ramos Lopes</a>, Tourism<br><a href="#">Regina Aparecida Delfino</a>, Graphic Arts<br><a href="#">Marta Margarida S. Dionísio</a>, Languages<br><a href="#">Ana Cláudia Pires da Silva</a>, Management<br><br><strong>Scientific Board</strong><br>Composed of all integrated members.<br><br><strong>Advisory Board</strong><br>Ana María Calvo Manuel, Faculty of Fine Arts, Completeness University of Madrid, Spain.<br>Chao Gejin, Institute of Oral Tradition, Chinese Academy of Social Sciences.<br>José Julio García Arranz, University of Extremadura, Spain.<br>Laurent Tissot, University of Neuchâtel, Switzerland.<br>Maria Filomena Guerra, Panthéon Sorbonne University, Nanterre, France.<br>Zoltán Somhegyi, Károli Gáspár University, Budapest, Hungary.<br><br>&nbsp;</p>
'
WHERE id=4;
UPDATE technart.areas_website
SET titulo='Novas Admissões', texto='
                        <p>A admissão de novos membros à equipa de investigação do TECHN&amp;ART, integrados ou colaboradores, processa-se através de proposta ao conselho científico. O/A candidado/a deve preencher o formulário com as informações e a documentação necessária.<br><br>
                            A admissão requererá que o/a candidado/a seja proposto/a por um membro integrado do TECHN&amp;ART, servindo para o efeito a carta de recomendação pedida no formulário.<br>
                        </p>
                        <p>O/A candidato deverá também consultar o                            <a href="https://drive.google.com/file/d/1P9hbWdVyB2YY7ySQNBWd8MegSVx4HEVt/view">
                                regulamento geral do TECHN&amp;ART.                            </a>
                        </p>
                        <br>
                        <a style="display: inline-block; padding: 5px 25px; background-color:#333F50; border: 2px solid #000000; color: #ffffff; border-radius: 0; 
                     -webkit-transition: all 0.3s; transition: all 0.3s;  font-family: ''Quicksand'', sans-serif;  font-size: 20px;" href="admissao.php">
                            Preencher Formulário                        </a>
                    ', fotografia='technart_color.png', titulo_en='New Admissions', texto_en='<p>The admission of new members to the TECHN&amp;ART research team, whether integrated or collaborators, is processed through a proposal to the scientific board. The candidate must fill out the form with the necessary information and documentation.<br><br>
Admission will require the candidate to be proposed by an integrated member of TECHN&amp;ART, with the recommendation letter requested in the form serving this purpose.<br>
</p>
<p>The candidate should also consult the <a href="https://drive.google.com/file/d/1P9hbWdVyB2YY7ySQNBWd8MegSVx4HEVt/view">TECHN&amp;ART general regulations</a>.</p>
<br>
<a style="display: inline-block; padding: 5px 25px; background-color:#333F50; border: 2px solid #000000; color: #ffffff; border-radius: 0; 
-webkit-transition: all 0.3s; transition: all 0.3s; font-family: ''Quicksand'', sans-serif; font-size: 20px;" href="admissao.php">Fill out Form</a>
'
WHERE id=5;
UPDATE technart.areas_website
SET titulo='Link Regulamentos', texto='<p>.\\assets\\regulamentos\\regulamentogeral.pdf</p>', fotografia=NULL, titulo_en=NULL, texto_en=NULL
WHERE id=6;`
